--MODULE 1 USER DETAILS
CREATE SEQUENCE S INCREMENT BY 1 START WITH 11223310;
DROP SEQUENCE S;

CREATE TABLE USER_DETAILS(USER_ID NUMBER PRIMARY KEY ,NAME VARCHAR2(50) NOT NULL,
                          EMAIL VARCHAR2(100)NOT NULL,NEW_PASSWORD VARCHAR2(50)NOT NULL,
                          CONFIRM_PASSWORD VARCHAR(50) NOT NULL,MOBILE_NUMBER NUMBER NOT NULL,
                          CREATED_DATE TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          UNIQUE(EMAIL));
DESC USER_DETAILS;
DROP TABLE USER_DETAILS;
INSERT INTO USER_DETAILS (USER_ID,NAME,EMAIL,NEW_PASSWORD,CONFIRM_PASSWORD,MOBILE_NUMBER)
                   VALUES(S.NEXTVAL,'DHARSHINI','dharshinagen@gmail.com','dharsh123','dharsh123',9876543210);
SELECT * FROM USER_DETAILS;
DELETE  USER_DETAILS WHERE USER_ID=1;

--MODULE 2 ACCOUNT DETAILS
CREATE  TABLE ACCOUNT_DETAILS(ACCOUNT_NUMBER NUMBER PRIMARY KEY,ACCOUNT_TYPE VARCHAR(50) NOT NULL,
                        USER_ID NUMBER NOT NULL,FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS(USER_ID),
                         ACCOUNT_HOLDER VARCHAR(50),ADDRESS VARCHAR(200) NOT NULL,
                        CITY VARCHAR2(20) NOT NULL,PINCODE NUMBER,DOB DATE NOT NULL,MOBILE_NUMBER NUMBER NOT NULL,
                        EMAIL VARCHAR2(100),BRANCH_CODE NUMBER NOT NULL,BALANCE NUMBER);
DESC ACCOUNT_DETAILS;
DROP TABLE ACCOUNT_DETAILS;
SELECT * FROM ACCOUNT_DETAILS;

--MODULE 3 DEPOSITS(fixed deposit,recurring deposit)
CREATE TABLE DEPOSITS(ID NUMBER PRIMARY KEY,CUSTOMER_ID NUMBER,FOREIGN KEY (CUSTOMER_ID) REFERENCES USER_DETAILS(USER_ID),
                      CUSTOMER_TYPE VARCHAR(20) NOT NULL,DEPOSIT_TYPE VARCHAR(30)NOT NULL,AMOUNT NUMBER NOT NULL,
                      DATE_OF_DEPOSIT_TYPE DATE,TENURE DATE,RATE_OF_INTEREST NUMBER,MATURITY_DATE DATE,MATURITY_VALUE NUMBER);
DESC DEPOSITS;
DROP TABLE DEPOSITS;
SELECT * FROM DEPOSITS;

--MODULE 4 LOANS
 CREATE TABLE LOANS(LOAN_NUMBER NUMBER PRIMARY KEY,ACCOUNT_NUMBER NUMBER,FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT_DETAILS(ACCOUNT_NUMBER),
                    LOAN_TYPE VARCHAR(50) NOT NULL,DESCRIPTION VARCHAR(100) ,LOAN_AMOUNT NUMBER NOT NULL,DURATION_OF_LOAN NUMBER NOT NULL,
                    INTEREST_RATE NUMBER NOT NULL,INTEREST_AMOUNT NUMBER NOT NULL,MONTHLY_PAYMENT NUMBER NOT NULL);
 DESC LOANS;
 DROP TABLE LOANS;
 SELECT * FROM LOANS;


                        
